name: Publish Package to GitHub Packages

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.7'
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Publish to GitHub Packages
      run: ./gradlew publishMavenKotlinPublicationToGitHubPackagesRepository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GitHubPackagesUsername: ${{ github.actor }}
        GitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
